version: "3"

volumes:
  pgsql:
    driver: local

networks:
  quiz-network:
    driver: bridge

services:
  backend:
    container_name: quiz_api_backend
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - pgsql
      - redis
    volumes:
      - ./:/var/www
    networks:
      - quiz-network
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis

  webserver:
    image: nginx:1.25.3
    container_name: quiz_api_webserver
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
    depends_on:
      - backend
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - quiz-network

  redis:
    image: redis:7.2.2-alpine
    container_name: quiz_api_redis
    restart: unless-stopped
    command: redis-server --requirepass 'password'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - quiz-network

  pgsql:
    image: 'postgres:16.0-alpine'
    container_name: quiz_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz_password
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - quiz-network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "quiz",
          "-U",
          "quiz"
        ]
      retries: 3
      timeout: 5s
