version: "3.4"

volumes:
  pgsql:
    driver: local

networks:
  network:
    driver: bridge

services:
  backend:
    container_name: quiz_api_backend
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: quiz_api_backend
    restart: unless-stopped
    tty: true
    depends_on:
      - pgsql
      - redis
    volumes:
      - ./:/var/www
    networks:
      - network
    env_file:
      - ./.env
    environment:
      CONTAINER_ROLE: backend
  
  migrate:
    container_name: quiz_api_migrate
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: quiz_api_roles
    restart: on-failure
    tty: true
    depends_on:
      - backend
    volumes:
      - ./:/var/www
    networks:
      - network
    env_file:
      - ./.env
    environment:
      CONTAINER_ROLE: migrate

  #scheduler:
  #  container_name: quiz_api_scheduler
  #  build:
  #    context: ./
  #    dockerfile: ./docker/php/Dockerfile
  #    target: quiz_api_roles
  #  restart: unless-stopped
  #  tty: true
  #  depends_on:
  #    - backend
  #  volumes:
  #    - ./:/var/www/html
  #  networks:
  #    - network
  #  env_file:
  #    - ./.env
  #  environment:
  #    CONTAINER_ROLE: scheduler

  queue:
    container_name: quiz_api_queue
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: quiz_api_roles
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
    volumes:
      - ./:/var/www/html
    networks:
      - network
    env_file:
      - ./.env
    environment:
      CONTAINER_ROLE: queue

  websockets:
    container_name: quiz_api_websockets
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: quiz_api_roles
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
    volumes:
      - ./:/var/www/html
    networks:
      - network
    env_file:
      - ./.env
    environment:
      CONTAINER_ROLE: websockets

  webserver:
    image: nginx:1.25.3
    container_name: quiz_api_webserver
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_NGINX_PORT:-8080}:80'
    depends_on:
      - backend
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network

  redis:
    image: redis:7.2.2-alpine
    container_name: quiz_api_redis
    restart: unless-stopped
    command: redis-server --requirepass 'password'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - network

  pgsql:
    image: 'postgres:16.0-alpine'
    container_name: quiz_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: quiz
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz_password
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - network
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "quiz",
          "-U",
          "quiz"
        ]
      retries: 3
      timeout: 5s
